# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ea9f55797de10ad7301c6635e168e7dae1df7105307d954e0ad7ef2876247443fd6de1d4e7e941926f91e55789112b940c92f850feafea2345b554a79239baa

test:
  secret_key_base: 123071024109a665df3ca961be2412599a9de269efff6a8e4839b3926fe8a078efa993b004668c176f216aef3e4feb1bb07039f79c0548fbab6be3e868245684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
